### ISSUE TITLE
Annotating test data failed 

### ISSUE THREAD

**Issue by imalsoft9** [asrhou/scMatch#15]
Hi,
Previously I  run scMatch using the current release and I obtained nice annotation result, however, recently, I tried to use it again under python3.9 and got error with scMatch.py. I confirmed that the required modules are installed: 
 ########################
python3.9 -m pip install numpy
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (1.19.5)
python3.9 -m pip install pandas
Requirement already satisfied: pandas in /usr/lib/python3/dist-packages (1.1.5)
python3.9 -m pip install scipy
Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (1.6.0)

I used the test dataset GSE81861_Cell_Line_COUNT.csv, 

~/scMatch$  python3.9 scMatch.py --refDS refDB/FANTOM5 --dFormat csv --testDS testData/GSE81861_Cell_Line_COUNT.csv

Output, 
Input data:
Reference species: human
The folder of reference dataset(s): refDB/FANTOM5
Test species: human
The format of the test dataset: csv
Test data are in the file: GSE81861_Cell_Line_COUNT.csv
The correlation method: s
Keep genes with zero expression level: yes
The number of cores to use: 1
===================================================
##########loading test data
test dataset shape: 57241 genes, 561 samples
##########annotating test data with human data
Traceback (most recent call last):
  File "/home/imad-a/scMatch/scMatch.py", line 357, in <module>
    main(testType, opt.dFormat, opt.testDS, opt.testGenes, opt.refDS, refTypeList, keepZeros, testMethodList, opt.coreNum)
  File "/home/imad-a/scMatch/scMatch.py", line 197, in main
    AnnSCData(testType, em, refDS, refType, hidSpecDict[refType], keepZeros, testMethod, coreNum, savefolder)
  File "/home/imad-a/scMatch/scMatch.py", line 92, in AnnSCData
    refDB = refDB.ix[~refDB.index.duplicated(keep='first'),]
  File "/usr/lib/python3/dist-packages/pandas/core/generic.py", line 5141, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ix'

Any suggestion to overcome this issue.

**Comment by danielsu0523** [comment]
Hi @imalsoft9 , you may update the code that @matt-sd-watson  have addressed on [pull requests]([matt-sd-watson](https://github.com/matt-sd-watson)). It works for me. Thanks Matt!
