### ISSUE TITLE
Issue when running Toterm.py

### ISSUE THREAD

**Issue by heeroena** [asrhou/scMatch#5]
Dear Admin

I run into the following errorr when I run the toTerms.py command in anaconda prompt (below).
I am not that well versed in programming so I am not sure what this means. I hope you have an idea.
kind regards
`Traceback (most recent call last):
  File "toTerms.py", line 160, in <module>
    main(splFileList, opt.refDS, opt.coreNum)
  File "toTerms.py", line 94, in main
    mapDict = json.load(json_file)
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)`

**Comment by asrhou** [comment]
Hi there,

Sorry for the late response. It seems that the json file is changed. Can I have a look at your 'human_samples_oto.txt' file?

Cheers,
Rui
